# -*- coding: utf-8 -*-
"""
Created on Wed Sep  1 06:15:15 2021

@author: dell
"""
v = {
"Wimbledon Men Singles":["https://www.premierbet.com.gh/#/sports/all/1047157/"],
"French Open Men Singles":["https://www.premierbet.com.gh/#/sports/all/1047159/"],
"Austrialian Open Men Singles":["https://www.premierbet.com.gh/#/sports/all/1047158/"],
"US Open Men Singles":["https://www.premierbet.com.gh/#/sports/all/1046985/"],
"US OPEN MEN DOUBLE":["https://www.premierbet.com.gh/#/sports/all/1047206/"],
"ATP CHALLENGER COMO ITALY MEN SINGLES":["https://www.premierbet.com.gh/#/sports/all/1075953/"],
"ATP CHALLENGER COMO ITALY MEN DOUBLES":["https://www.premierbet.com.gh/#/sports/all/1075964/"],  
"ATP CHALLENGER SAINT TROPEZ FRANCE MEN SINGLES":["https://www.premierbet.com.gh/#/sports/all/1075961/"],
"ATP WINSTON SALEM":["https://www.premierbet.com.gh/#/sports/all/1075850/"],
"WTA WIMBLEDON WOMEN SINGLES":["https://www.premierbet.com.gh/#/sports/all/1047181/"],
"WTA AUSTRALIAN OPEN WOMEN SINGLES":["https://www.premierbet.com.gh/#/sports/all/1047570/"],
"WTA US OPEN WOMEN SINGLES":["https://www.premierbet.com.gh/#/sports/all/1046986/"],
"WTA CLEVELAND USA WOMEN SINGLES":["https://www.premierbet.com.gh/#/sports/all/1075848/"],
"WTA CHICAGO USA WOMEN SINGLES":["https://www.premierbet.com.gh/#/sports/all/1075849/"],
"WTA CLEVELAND USA WOMEN DOUBLES":["https://www.premierbet.com.gh/#/sports/all/1075857/"],
"ATP CHALLENGER WARSAW,POLAND MEN SINGLES":["https://www.premierbet.com.gh/#/sports/all/1075854/"],
"ATP CHALLENGER BARLETTA,ITALY MEN SINGLES":["https://www.premierbet.com.gh/#/sports/all/1075855/"],
"ATP CHALLENGER PRAGUE 3,CZECH REPUBLIC MEN SINGLES":["https://www.premierbet.com.gh/#/sports/all/1075856/"],
"ATP CHALLENGER BARLETTA,ITALY MEN DOUBLE":["https://www.premierbet.com.gh/#/sports/all/1075868/"],
"ATP CHALLENGER WARSAW, POLAND MEN DOUBLES":["https://www.premierbet.com.gh/#/sports/all/1075869/"],
"ATP CHALLENGER PRAGUE 3, CZECH REPUBLIC MEN DOUBLES":["https://www.premierbet.com.gh/#/sports/all/1075870/"],
"ATP CHALLENGER MANACOR,MALLORCA SPAIN MEN SINGLES":["https://www.premierbet.com.gh/#/sports/all/1075975/"],
"ATP CHALLENGER MANACOR,MALLORCA  SPAIN MEN DOUBLE":["https://www.premierbet.com.gh/#/sports/all/1075976/"],
"ITF TUNISIA F34, MEN SINGLES":["https://www.premierbet.com.gh/#/sports/all/1072350/"],
"ITF TUNISIA F34, MEN DOUBLES":["https://www.premierbet.com.gh/#/sports/all/1072369/"],
"ITF BELGIUM F3, MEN SINGLES":["https://www.premierbet.com.gh/#/sports/all/1075853/"],
"ITF POLAND F3, MEN SINGLES":["https://www.premierbet.com.gh/#/sports/all/1075859/"],
"ITF ITALY F8, MEN SINGLES":["https://www.premierbet.com.gh/#/sports/all/1075862/"],
"ITF ITALY F8, MEN DOUBLES":["https://www.premierbet.com.gh/#/sports/all/1075902/"],
"ITF BELGIUM F3, MEN DOUBLES":["https://www.premierbet.com.gh/#/sports/all/1075893/"],
"ITF SLOVAKIA F7, MEN DOUBLES":["https://www.premierbet.com.gh/#/sports/all/1075895/"],
"ITF SWITZERLAND F7, MEN DOUBLES":["https://www.premierbet.com.gh/#/sports/all/1075896/"],
"ITF GERMANY F8, MEN DOUBLES":["https://www.premierbet.com.gh/#/sports/all/1075897/"],
"ITF SPAIN F20, MEN DOUBLES":["https://www.premierbet.com.gh/#/sports/all/1075898/"],
"ITF AUSTRIA F1, MEN DOUBLES":["https://www.premierbet.com.gh/#/sports/all/1075900/"],
"ITF SPAIN F20, MEN SINGLES:":["https://www.premierbet.com.gh/#/sports/all/1075864/"],
"ITF AUSTRIA F1, MEN SINGLES:":["https://www.premierbet.com.gh/#/sports/all/1075865/"],
"ITF GERMANY F8, MEN SINGLES":["https://www.premierbet.com.gh/#/sports/all/1075876/"],
"ITF SWITZERLAND F7, MEN SINGLES":["https://www.premierbet.com.gh/#/sports/all/1075878/"],
"ITF SLOVAKIA F7, MEN SINGLES":["https://www.premierbet.com.gh/#/sports/all/1075879/"],
"ITF POLAND F3, MEN DOUBLES":["https://www.premierbet.com.gh/#/sports/all/1075889/"],
"ITF TUNISIA 34A, WOMEN SINGLES":["https://www.premierbet.com.gh/#/sports/all/1072263/"],
"ITF TUNISIA 34A, WOMEN DOUBLES":["https://www.premierbet.com.gh/#/sports/all/1072264/"],
"ITF BELGIUM 01A, WOMEN SINGLES":["https://www.premierbet.com.gh/#/sports/all/1075860/"],
"ITF AUSTRIA 01A, WOMEN SINGLES":["https://www.premierbet.com.gh/#/sports/all/1075861/"],
"ITF SWITZERLAND 05A, WOMEN SINGLES":["https://www.premierbet.com.gh/#/sports/all/1075863/"],
"ITF BELGIUM 01A, WOMEN DOUBLES":["https://www.premierbet.com.gh/#/sports/all/1075901/"],
"ITF KAZAKHSTAN 09A, WOMEN DOUBLES":["https://www.premierbet.com.gh/#/sports/all/1075888/"],
"ITF CZECH REPUBLIC 07A, WOMEN SINGLES":["https://www.premierbet.com.gh/#/sports/all/1075890/"],
"ITF UKRAINE 03A, WOMEN DOUBLES":["https://www.premierbet.com.gh/#/sports/all/1075891/"],
"ITF SWITZERLAND 05A, WOMEN DOUBLES":["https://www.premierbet.com.gh/#/sports/all/1075892/"],
"ITF GERMANY 07A, WOMEN DOUBLES":["https://www.premierbet.com.gh/#/sports/all/1075894/"],
"ITF AUSTRIA 01A, WOMEN DOUBLES":["https://www.premierbet.com.gh/#/sports/all/1075899/"],
"ITF SPAIN 21A, WOMEN SINGLES":["https://www.premierbet.com.gh/#/sports/all/1075877/"],
"ITF SPAIN 21A, WOMEN DOUBLES":["https://www.premierbet.com.gh/#/sports/all/1075887/"],
"ITF SWITZERLAND 05A, WOMEN DOUBLES":["https://www.premierbet.com.gh/#/sports/all/1075892/"],
"ITF GERMANY 07A, WOMEN DOUBLES":["https://www.premierbet.com.gh/#/sports/all/1075894/"],
"ITF SPAIN F21, MEN SINGLES":["https://www.premierbet.com.gh/#/sports/all/1063380/"],
"ITF SPAIN F21, MEN DOUBLES":["https://www.premierbet.com.gh/#/sports/all/1063778/"],
"ITF TUNISIA F35, MEN SINGLES":["https://www.premierbet.com.gh/#/sports/all/1072450/"],
"ITF TUNISIA F35, MEN DOUBLES":["https://www.premierbet.com.gh/#/sports/all/1072470/"],
"ITF FRANCE F11, MEN SINGLES":["https://www.premierbet.com.gh/#/sports/all/1075950/"],
"ITF SWITZERLAND F5 MEN SINGLES":["https://www.premierbet.com.gh/#/sports/all/1075951/"],
"ITF SLOVAKIA F9, MEN DOUBLES":["https://www.premierbet.com.gh/#/sports/all/1075993/"],
"ITF AUSTRIA F3, MEN DOUBLES":["https://www.premierbet.com.gh/#/sports/all/1075979/"],
"ITF SWITZERLAND F5, MEN DOUBLES":["https://www.premierbet.com.gh/#/sports/all/1075980/"],
"ITF UKRAINE F4, MEN DOUBLES":["https://www.premierbet.com.gh/#/sports/all/1075987/"],
"ITF FRANCE F11, MEN DOUBLES":["https://www.premierbet.com.gh/#/sports/all/1075989/"],
"ITF MONTENEGRO F1, MEN DOUBLES":["https://www.premierbet.com.gh/#/sports/all/1075990/"],
"ITF GERMANY F10, ,MEN DOUBLES":["https://www.premierbet.com.gh/#/sports/all/1075992/"],
"ITF AUSTRIA F3, MEN SINGLES":["https://www.premierbet.com.gh/#/sports/all/1075954/"],
"ITF EGJPYT F36,MEN SINGLES":["https://www.premierbet.com.gh/#/sports/all/1075959/"],
"ITF MONTENEGRO F1,MEN SINGLES":["https://www.premierbet.com.gh/#/sports/all/1075963/"],
"ITF GERMANY F10, MEN SINGLES":["https://www.premierbet.com.gh/#/sports/all/1075972/"],
"ITF SLOVAKIA F9, MEN SINGLES":["https://www.premierbet.com.gh/#/sports/all/1075974/"],
"ITF CZECH REPUBLIC F5, MEN DOUBLES":["https://www.premierbet.com.gh/#/sports/all/1075978/"],
"ITF TUNISIA 35A, WOMEN SINGLES":["https://www.premierbet.com.gh/#/sports/all/1072362/"],
"ITF TUNISIA 35A, WOMEN DOUBLES":["https://www.premierbet.com.gh/#/sports/all/1072370"],
"ITF AUSTRIA 02A, WOMEN SINGLES":["https://www.premierbet.com.gh/#/sports/all/1075955/"],
"ITF CZECH REPUBLIC 05A, WOMEN SINGLES":["https://www.premierbet.com.gh/#/sports/all/1075956/"],
"ITF SPAIN 15A,WOMEN SINGLES":["https://www.premierbet.com.gh/#/sports/all/1075958/"],
"ITF SWITZERLAND 04A, WOMEN DOUBLES":["https://www.premierbet.com.gh/#/sports/all/1075985/"],
"ITF FRANCE 02A, WOMEN DOUBLES":["https://www.premierbet.com.gh/#/sports/all/1075986/"],
"ITF ITALY 09A, WOMEN DOUBLES":["https://www.premierbet.com.gh/#/sports/all/1075988/"],
"ITF AUSTRIA 02A, WOMEN DOUBLES":["https://www.premierbet.com.gh/#/sports/all/1075991/"],
"ITF EGYPT 36A,WOMEN SINGLES":["https://www.premierbet.com.gh/#/sports/all/1075960/"],
"ITF SWITZERLAND 04A,WOMEN SINGLES":["https://www.premierbet.com.gh/#/sports/all/1075967/"],
"ITF FRANCE 20A, WOMEN SINGLES":["https://www.premierbet.com.gh/#/sports/all/1075968/"],
"ITF ITALY 09A, WOMEN SINGLES":["https://www.premierbet.com.gh/#/sports/all/1075973/"],
"ITF CZECH REPUBLIC 05A,WOMEN DOUBLES":["https://www.premierbet.com.gh/#/sports/all/1075981/"],
"ITF EGYPT 36A, WOMEND DOUBLES":["https://www.premierbet.com.gh/#/sports/all/1075983/"]
}



for i,b in v.items():
    if "https://www.premierbet.com.gh/#/sports/all/1075983/" in b[0]:
        print("y")
